openapi: 3.0.1
info:
  title: TodoAPI
  version: '1.1'
paths:
  /todos:
    get:
      parameters:
        - name: new
          in: header
          schema:
            type: number
          required: false
        - name: tDah
          in: query
          schema:
            type: string
          required: true
        - name: test
          in: header
          schema:
            type: string
          required: false

      responses:
        '200':
          description: okay
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/TodoRead'
                required:
                  - todos
components:
  schemas:
    TodoRead:
      type: object
      properties:
        name:
          type: string
        status:
          type: string
        created_at:
          type: string
        example:
          type: string
          format: date-time
          example: '2020-01-01T00:00:00.000Z'
      required:
        - status
